--############ Question 1 #####################
CREATE TABLE EMP2
AS SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = -1;

INSERT INTO EMP2
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--############ Question 2 A #####################
CREATE TABLE DEPARTMENT(
    ID NUMBER(7) DEFAULT 1,
    NAME VARCHAR2(25)
);

INSERT INTO DEPARTMENT
SELECT DEPTS.DEPARTMENT_ID,  DEPTS.DEPARTMENT_NAME FROM DEPTS;

--############ Question 2 B #####################
ALTER TABLE DEPARTMENT
ADD LOCATION VARCHAR2(100);

--############ Question 2 C #####################
TRUNCATE TABLE DEPARTMENT;


--############ Question 3 #####################
CREATE TABLE EMPLOYEE_BKP
AS SELECT EMPLOYEE_ID,LAST_NAME,EMAIL,SALARY,DEPARTMENT_ID FROM EMPLOYEES;

ALTER TABLE EMPLOYEE_BKP
ADD CONSTRAINT EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_BKP
ADD CONSTRAINT EMAIL_U PRIMARY KEY(EMAIL);

--############ Question 4 A #####################
CREATE OR REPLACE VIEW EMP_VU AS
    SELECT EMPLOYEE_ID, LAST_NAME AS title_name , DEPARTMENT_ID
    FROM EMPLOYEES
WITH CHECK OPTION;;

--############ Question 4 B #####################
CREATE OR REPLACE VIEW EMP_VU AS
    SELECT EMPLOYEE_ID, LAST_NAME AS title_name , DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20
WITH CHECK OPTION;;

--############ Question 5 #####################
CREATE SEQUENCE DEPT_ID_SEQ
START WITH 400
MAXVALUE 1000
INCREMENT BY 10;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
            VALUES (DEPT_ID_SEQ.nextval,'ITI',100,1000);